version: '3.8'
services:
  web:
    build: .
    command: bash -c "python manage.py wait_for_db && python manage.py test && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: job_aggregator
      POSTGRES_USER: job_aggregator_user
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: